# Author: Studios TKOH!
spring.application.name=producto-manager
server.port=8082

# Habilitamos DDL validate
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=false
spring.jpa.open-in-view=false
spring.jpa.properties.hibernate.format_sql=true

# DataSource con placeholders y valores por defecto
spring.datasource.url=jdbc:mysql://${MYSQL_HOST}:${MYSQL_PORT:3306}/${MYSQL_DATABASE}?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=America/Lima
spring.datasource.username=${MYSQL_USER}
spring.datasource.password=${MYSQL_PASSWORD}